services:    
  frontend:
    build: frontend/
    env_file:
      - path: ./dockerenv
        required: true
    network_mode: "host"
    volumes:
      - "./frontend:/app"
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000

  db:
    image: mysql
    restart: always
    healthcheck:
      test: mysqladmin ping -h localhost
      timeout: 20s
      retries: 10
      start_period: 2s
    ports:
      - 3306:3306
      
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel

  backend-init:
    build: backend/
    command: php artisan migrate:fresh --seed
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - "./backend:/var/www/html"
    env_file:
      - path: ./dockerenv
        required: true
  
  backend:
    build: backend/
    depends_on:
      - backend-init
    env_file:
      - path: ./dockerenv
        required: true
    volumes:
      - "./backend:/var/www/html"
    ports:
      - 8000:8000

  worker:
    build: backend/
    command: php artisan queue:listen
    depends_on:
       backend-init: 
        condition: service_completed_successfully
        restart: true
    volumes:
      - "./backend:/var/www/html"
    env_file:
      - path: ./dockerenv
        required: true