services:    
  frontend:
    build: frontend/
    env_file:
      - path: ./dockerenv
        required: true
    network_mode: "service:backend"
    volumes:
      - "./frontend:/app"
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
  
  backend:
    build: backend/
    depends_on:
      - backend-init

    env_file:
      - path: ./dockerenv
        required: true

    volumes:
      - "./backend:/var/www/html"
    ports:
      - 8000:8000
      - 3000:3000
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: laravel
      MARIADB_USER: laravel
      MARIADB_PASSWORD: laravel
  backend-init:
    build: backend/
    command: php artisan migrate:fresh --seed
    depends_on:
      - db
    volumes:
      - "./backend:/var/www/html"
    env_file:
      - path: ./dockerenv
        required: true
  worker:
    build: backend/
    command: php artisan queue:listen
    depends_on:
      - backend-init
    volumes:
      - "./backend:/var/www/html"
    env_file:
      - path: ./dockerenv
        required: true